-- MySQL Script generated by MySQL Workbench
-- Tue May 10 12:53:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema soundSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `soundSystem` ;

-- -----------------------------------------------------
-- Schema soundSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soundSystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `soundSystem` ;

-- -----------------------------------------------------
-- Table `soundSystem`.`categoryUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`categoryUser` (
  `idcategoryUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoryUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundSystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  `idcategoryUsers` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `fk_usuarios_categorias`
    FOREIGN KEY (`idcategoryUsers`)
    REFERENCES `soundSystem`.`categoryUser` (`idcategoryUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_usuarios_categorias_idx` ON `soundSystem`.`user` (`idcategoryUsers` ASC) VISIBLE;

CREATE INDEX `fk_usuarios_categorias` ON `soundSystem`.`user` (`idcategoryUsers` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `soundSystem`.`categorysProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`categorysProducts` (
  `idcategorysProducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorysProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundSystem`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`brands` (
  `idbrands` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbrands`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundSystem`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `img` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `discount` DECIMAL(2) NULL DEFAULT NULL,
  `idcategorysProducts` INT NOT NULL,
  `idbrands` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  CONSTRAINT `fk_productos_categorysProducts1`
    FOREIGN KEY (`idcategorysProducts`)
    REFERENCES `soundSystem`.`categorysProducts` (`idcategorysProducts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_productos_brands1`
    FOREIGN KEY (`idbrands`)
    REFERENCES `soundSystem`.`brands` (`idbrands`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_productos_categorysProducts1_idx` ON `soundSystem`.`product` (`idcategorysProducts` ASC) VISIBLE;

CREATE INDEX `fk_productos_brands1_idx` ON `soundSystem`.`product` (`idbrands` ASC) VISIBLE;

CREATE INDEX `fk_productos_categorysProducts1` ON `soundSystem`.`product` (`idcategorysProducts` ASC) VISIBLE;

CREATE INDEX `fk_productos_brands1` ON `soundSystem`.`product` (`idbrands` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `soundSystem`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`invoice` (
  `idinvoice` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idinvoice`),
  CONSTRAINT `fk_invoice_usuarios1`
    FOREIGN KEY (`iduser`)
    REFERENCES `soundSystem`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_invoice_usuarios1_idx` ON `soundSystem`.`invoice` (`iduser` ASC) VISIBLE;

CREATE INDEX `fk_invoice_usuarios1` ON `soundSystem`.`invoice` (`iduser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `soundSystem`.`detailBuy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soundSystem`.`detailBuy` (
  `iddetailBuy` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `tax` DECIMAL(4) NULL DEFAULT NULL,
  `totalAmount` INT NULL DEFAULT NULL,
  `totalBuy` INT NULL DEFAULT NULL,
  `idproduct` INT NOT NULL,
  `idinvoice` INT NOT NULL,
  PRIMARY KEY (`iddetailBuy`),
  CONSTRAINT `fk_detailBuy_product1`
    FOREIGN KEY (`idproduct`)
    REFERENCES `soundSystem`.`product` (`idproduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detailBuy_invoice1`
    FOREIGN KEY (`idinvoice`)
    REFERENCES `soundSystem`.`invoice` (`idinvoice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_detailBuy_product1_idx` ON `soundSystem`.`detailBuy` (`idproduct` ASC) VISIBLE;

CREATE INDEX `fk_detailBuy_invoice1_idx` ON `soundSystem`.`detailBuy` (`idinvoice` ASC) VISIBLE;

CREATE INDEX `fk_detailBuy_product1` ON `soundSystem`.`detailBuy` (`idproduct` ASC) VISIBLE;

CREATE INDEX `fk_detailBuy_invoice1` ON `soundSystem`.`detailBuy` (`idinvoice` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
